export const lofi = [
    {
        name: '1 phút',
        singer: 'AndieZ',
        album: 'Lofi',
        music: './asset/music/lofi/1phut.mp3',
        albumCover: '/asset/music/lofi/lofi.webp',
        img: '/asset/music/lofi/',
        lyriss: '',
    },
    {
        name: 'Anh đã từ bỏ rồi đấy',
        singer: 'Nguyenn x Aric',   
        album: 'Lofi',
        music: './asset/music/lofi/adatuboroiday.mp3',
        albumCover: '/asset/music/lofi/lofi.webp',
        img: '/asset/music/lofi/anhdatuboroiday.jpg',
        lyriss: '',
    },
    {
        name: 'Chờ đợi có đáng sợ',
        singer: 'AndieZ',
        album: 'Lofi',
        music: './asset/music/lofi/chodoi.mp3',
        albumCover: '/asset/music/lofi/lofi.webp',
        img: '/asset/music/lofi/chodoi.jpg',
        lyriss: '',
    },
    {
        name: 'Gió',
        singer: 'J97',
        album: 'Lofi',
        music: './asset/music/lofi/gio.mp3',
        albumCover: '/asset/music/lofi/lofi.webp',
        img: '/asset/music/lofi/gio.jpg',
        lyriss: '',
    },
    {
        name: 'Hình như ta thích nhau',
        singer: 'Doãn Hiếu',
        album: 'Lofi',
        music: '/asset/music/lofi/hinhnhutathichnhau.mp3',
        albumCover: '/asset/music/lofi/lofi.webp',
        img: '/asset/music/lofi/hinhnhu.jpg',
        lyriss: '',
    },
    {
        name: 'Kẻ theo đuổi ánh sáng',
        singer: 'Huy Vạc',
        album: 'Lofi',
        music: '/asset/music/lofi/ketheodoianhsang.mp3',
        albumCover: '/asset/music/lofi/lofi.webp',
        img: '/asset/music/lofi/ketheodoi.jpg',
        lyriss: '',
    },
    {
        name: 'Hẹn em yêu lần thứ 2',
        singer: 'Nguyenn x DangTuanVu',
        album: 'Lofi',
        music: './asset/music/lofi/henemlanyeuthu2.mp3',
        albumCover: '/asset/music/lofi/',
        img: '/asset/music/lofi/henem.jpg',
        lyriss: '',
    }
]